=== filippocostalli/esignum-cco/resources/PIndex.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:sincro="http://www.uni.com/U3011/sincro-v2/"
	   xmlns:xs="http://www.w3.org/2001/XMLSchema"
	   targetNamespace="http://www.uni.com/U3011/sincro-v2/"
	   elementFormDefault="qualified" attributeFormDefault="qualified">
	<xs:annotation>
		<xs:documentation xml:lang="en">DEFINITION OF SIMPLE TYPES</xs:documentation>
	</xs:annotation>
	<xs:simpleType name="Name">
		<xs:restriction base="xs:string" />
	</xs:simpleType>
	<xs:simpleType name="Version">
		<xs:restriction base="xs:string" />
	</xs:simpleType>
	<xs:simpleType name="Producer">
		<xs:restriction base="xs:string" />
	</xs:simpleType>	
	<xs:simpleType name="FirstName">
		<xs:restriction base="xs:string" />
	</xs:simpleType>
	<xs:simpleType name="LastName">
		<xs:restriction base="xs:string" />
	</xs:simpleType>
	<xs:simpleType name="FormalName">
		<xs:restriction base="xs:string" />
	</xs:simpleType>
	<xs:simpleType name="Path">
		<xs:restriction base="xs:anyURI" />
	</xs:simpleType>
	<xs:simpleType name="Description">
		<xs:restriction base="xs:string" />
	</xs:simpleType>
	<xs:simpleType name="Label">
		<xs:restriction base="xs:string" />
	</xs:simpleType>
	<xs:simpleType name="Type">
		<xs:restriction base="xs:string" />
	</xs:simpleType>
	<xs:simpleType name="Value">
		<xs:restriction base="xs:string" />
	</xs:simpleType>
	<xs:simpleType name="LawsAndRegulations">
		<xs:restriction base="xs:string" />
	</xs:simpleType>
	<xs:simpleType name="agentIDvalue">
		<xs:restriction base="xs:string">
			<xs:pattern value="(PAS|IDC|PNO|TIN|VAT|NTR|([A-Za-z0-9]{2}:))[A-Z]{2}\-[a-zA-Z0-9]+" />	
		</xs:restriction>
	</xs:simpleType>
	<xs:annotation>
		<xs:documentation xml:lang="en">DEFINITION OF ATTRIBUTES</xs:documentation>
	</xs:annotation>
	<xs:attribute name="language" type="xs:language" use="required" />
	<xs:attribute name="uri" type="xs:anyURI" fixed="http://www.uni.com/U3011/sincro-v2/PIndex.xsd" />
	<xs:attribute name="sincroVersion" type="xs:NMTOKEN" fixed="2.0" />
	<xs:attribute name="scheme" type="xs:string" />
	<xs:attribute name="holderRole">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="soggetto produttore" />
				<xs:enumeration value="soggetto proprietario" />
				<xs:enumeration value="soggetto possessore" />
				<xs:enumeration value="soggetto detentore" />
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	<xs:attribute name="agentType">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="natural person" />
				<xs:enumeration value="legal person" />
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	<xs:attribute name="signerRole" type="xs:string" />
	<xs:attribute name="expan" type="xs:string" />
	<xs:attribute name="nameRegistrationAuthority" type="xs:string" />
	<xs:attribute name="docHash" type="xs:string" />
	<xs:attribute name="hashFunction" type="xs:string" />
	<xs:attribute name="uriDoc" type="xs:anyURI" />
	<xs:attribute name="xmlSchema" type="xs:anyURI" />
	<xs:attribute name="derivation">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="onetoone" />
				<xs:enumeration value="manytoone" />
				<xs:enumeration value="onetomany" />
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	<xs:attribute name="encoding">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="7bit" />
				<xs:enumeration value="8bit" />
				<xs:enumeration value="base64" />
				<xs:enumeration value="binary" />
				<xs:enumeration value="quoted-printable" />
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	<xs:attribute name="extension" type="xs:string" />
	<xs:attribute name="format" type="xs:string" />
	<xs:attribute name="canonicalXML" type="xs:boolean" />
	<xs:attribute name="attachedTimeStamp" type="xs:boolean" />
	<xs:attribute name="normal" type="xs:dateTime" />
	<xs:annotation>
		<xs:documentation xml:lang="en">DEFINITION OF COMPLEX TYPES</xs:documentation>
	</xs:annotation>
        <xs:complexType name="EmbeddedMetadata">
                 <xs:complexContent>
                               <xs:extension base="xs:anyType"></xs:extension>
                 </xs:complexContent>
        </xs:complexType>
	<xs:complexType name="ID">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute ref="sincro:scheme" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="PIndexID">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute ref="sincro:scheme" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="Agent">
		<xs:sequence>
			<xs:element name="AgentID" type="sincro:AgentID" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="AgentName" type="sincro:AgentName" />
			<xs:element name="RelevantDocument" type="sincro:RelevantDocument" maxOccurs="unbounded" />
			<xs:element name="MoreInfo" type="sincro:MoreInfo" minOccurs="0" />
		</xs:sequence>
		<xs:attribute ref="sincro:agentType" use="required" />
	</xs:complexType>
	<xs:complexType name="RelevantDocument">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute ref="sincro:docHash" />
				<xs:attribute ref="sincro:hashFunction" />
				<xs:attribute ref="sincro:uriDoc" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="AgentID">
		<xs:simpleContent>
			<xs:extension base="sincro:agentIDvalue">
				<xs:attribute ref="sincro:expan" />
				<xs:attribute ref="sincro:nameRegistrationAuthority" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="ExternalMetadata">
		<xs:sequence>
			<xs:element name="ID" type="sincro:ID" />
			<xs:element name="Path" type="sincro:Path" />
			<xs:element name="Hash" type="sincro:Hash" />
			<xs:element name="MoreInfo" type="sincro:MoreInfo" minOccurs="0" />
		</xs:sequence>
		<xs:attribute ref="sincro:encoding" use="required" />
		<xs:attribute ref="sincro:extension" />
		<xs:attribute ref="sincro:format" use="required" />
	</xs:complexType>
	<xs:complexType name="MoreInfo">
		<xs:choice>
		        <xs:element name="EmbeddedMetadata" type="sincro:EmbeddedMetadata" />
		        <xs:element name="ExternalMetadata" type="sincro:ExternalMetadata" />
		</xs:choice>
		<xs:attribute ref="sincro:xmlSchema" use="required" />
	</xs:complexType>
	<xs:complexType name="Hash">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute ref="sincro:canonicalXML" />
				<xs:attribute ref="sincro:hashFunction" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="PreviousHash">
		<xs:simpleContent>
			<xs:extension base="xs:string">
			        <xs:attribute ref="sincro:canonicalXML" />
			        <xs:attribute ref="sincro:hashFunction" use="required"/>
			        <xs:attribute name="relatedPIndex" type="xs:string" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="CreatingApplication">
		<xs:sequence>
			<xs:element name="Name" type="sincro:Name" />
			<xs:element name="Version" type="sincro:Version" />
			<xs:element name="Producer" type="sincro:Producer" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PIndexSource">
		<xs:sequence>
			<xs:element name="ID" type="sincro:ID" />
			<xs:element name="Path" type="sincro:Path" />
			<xs:element name="Hash" type="sincro:Hash" />
		</xs:sequence>
		<xs:attribute ref="sincro:derivation" use="required" />
	</xs:complexType>
	<xs:complexType name="PVolumeSource">
		<xs:sequence>
			<xs:element name="ID" type="sincro:ID" />
			<xs:element name="PIndexID" type="sincro:PIndexID" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PVolumeGroup">
		<xs:sequence>
			<xs:element name="ID" type="sincro:ID" />
			<xs:element name="Label" type="sincro:Label" minOccurs="0" />
			<xs:element name="Description" type="sincro:Description" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PVolume">
		<xs:sequence>
			<xs:element name="ID" type="sincro:ID" />
                        <xs:element name="Label" type="sincro:Label" minOccurs="0" />
			<xs:element name="Description" type="sincro:Description" minOccurs="0" />
			<xs:element name="PVolumeSource" type="sincro:PVolumeSource" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="PVolumeGroup" type="sincro:PVolumeGroup" minOccurs="0" />
			<xs:element name="MoreInfo" type="sincro:MoreInfo" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="FileGroup">
		<xs:sequence>
			<xs:element name="ID" type="sincro:ID" />
			<xs:element name="Label" type="sincro:Label" minOccurs="0" />
			<xs:element name="Description" type="sincro:Description" minOccurs="0" />
			<xs:element name="File" type="sincro:File" maxOccurs="unbounded" />
			<xs:element name="Relation" type="sincro:Relation" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="MoreInfo" type="sincro:MoreInfo" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="File">
		<xs:sequence>
			<xs:element name="ID" type="sincro:ID" />
			<xs:element name="Path" type="sincro:Path" />
			<xs:element name="Hash" type="sincro:Hash" />
			<xs:element name="PreviousHash" type="sincro:PreviousHash" minOccurs="0" />
			<xs:element name="Relation" type="sincro:Relation" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="MoreInfo" type="sincro:MoreInfo" minOccurs="0" />
		</xs:sequence>
		<xs:attribute ref="sincro:encoding" use="required" />
		<xs:attribute ref="sincro:extension" />
		<xs:attribute ref="sincro:format" use="required" />
	</xs:complexType>
	<xs:complexType name="SelfDescription">
		<xs:sequence>
			<xs:element name="ID" type="sincro:ID" />
			<xs:element name="CreatingApplication" type="sincro:CreatingApplication" />
			<xs:element name="PIndexSource" type="sincro:PIndexSource" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="MoreInfo" type="sincro:MoreInfo" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="NameAndSurname">
		<xs:sequence>
			<xs:element name="FirstName" type="sincro:FirstName" />
			<xs:element name="LastName" type="sincro:LastName" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AgentName">
		<xs:choice>
			<xs:element name="NameAndSurname" type="sincro:NameAndSurname" />
			<xs:element name="FormalName" type="sincro:FormalName" />
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="Relation">
		<xs:sequence>
			<xs:element name="Type" type="sincro:Type" />
			<xs:element name="Value" type="sincro:Value" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Process">
		<xs:sequence>
			<xs:element name="Submitter" type="sincro:Agent" />
			<xs:element name="Holder" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="sincro:Agent">
							<xs:attribute ref="sincro:holderRole" use="required"/>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="AuthorizedSigner" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="sincro:Agent">
							<xs:attribute ref="sincro:signerRole" />
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="TimeReference" type="sincro:TimeReference" />
			<xs:element name="LawsAndRegulations" type="sincro:LawsAndRegulations" minOccurs="0" />
			<xs:element name="MoreInfo" type="sincro:MoreInfo" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TimeReference">
		<xs:choice>
			<xs:element name="TimeInfo" type="sincro:TimeInfo" />
			<xs:element name="TimeStamp" type="sincro:TimeStamp" />
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="TimeInfo">
		<xs:simpleContent>
			<xs:extension base="xs:dateTime">
				<xs:attribute ref="sincro:attachedTimeStamp" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="TimeStamp">
		<xs:simpleContent>
			<xs:extension base="xs:anyURI">
				<xs:attribute ref="sincro:encoding" use="required" />
				<xs:attribute ref="sincro:format" use="required" />
				<xs:attribute ref="sincro:normal" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="PIndex">
		<xs:sequence>
			<xs:element name="SelfDescription" type="sincro:SelfDescription" />
			<xs:element name="PVolume" type="sincro:PVolume" />
			<xs:element name="FileGroup" type="sincro:FileGroup" maxOccurs="unbounded" />
			<xs:element name="Process" type="sincro:Process" />
		</xs:sequence>
		<xs:attribute ref="sincro:language" />
		<xs:attribute ref="sincro:uri" use="required" />
		<xs:attribute ref="sincro:sincroVersion" use="required"/>
	</xs:complexType>
	<xs:annotation>
		<xs:documentation xml:lang="en"> Definition of root element </xs:documentation>
	</xs:annotation>
	<xs:element name="PIndex" type="sincro:PIndex" />
</xs:schema>

=== filippocostalli/esignum-cco/resources/idc_cco_unisincro2020.xml
<?xml version="1.0" encoding="UTF-8"?>
<PIndex xmlns="http://www.uni.com/U3011/sincro-v2/"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.uni.com/U3011/sincro-v2 PIndex.xsd"
 xmlns:sincro="http://www.uni.com/U3011/sincro-v2/" sincro:language="it"
 sincro:uri="http://www.uni.com/U3011/sincro-v2/PIndex.xsd" sincro:sincroVersion="2.0">
    <SelfDescription>
        <ID sincro:scheme="local">CCO-{{cartella-id}}-{{data-creazione}}</ID>
        <CreatingApplication>
            <Name>esignum</Name>
            <Version>2.0.0</Version>
            <Producer>Marno S.r.l.</Producer>
        </CreatingApplication>
    </SelfDescription>
    <PVolume>
        <ID sincro:scheme="recepta.regis">{{cartella-barcode}}</ID>
        <Label>CARTELLA CLINICA</Label>
        <Description>Indice cartella clinica ospedaliera</Description>
        <MoreInfo sincro:xmlSchema="https://www.esignum.it/schemas/cartellecliniche.xsd">
          <EmbeddedMetadata>
            <CartellaClinica
              id="{{cartella-id}}" barcode="{{cartella-barcode}}" codiceSdo="{{cartella-sdo-codice}}" anno="{{cartella-sdo-anno}}" dataRicovero="{{cartella-dataricovero|date:yyyy-MM-dd:SSSXXXXX}}"
              presidio="{{cartella-presidio-descrizione}}" reparto="{{cartella-reparto-descrizione}}" assistitoCognome="{{cartella-cognome}}" assistitnoNome="{{cartella-nome}}" assistitoCodiceFiscale="{{cartella-codicefiscale}}" />
          </EmbeddedMetadata>
        </MoreInfo>
    </PVolume>
    <FileGroup>
        <ID sincro:scheme="recepta.regis">{{cartella-id}}</ID>
        <Description>Lista dei documenti che compongono la CCO digitalizzata</Description>{% for documento in documenti %}
        <File sincro:encoding="binary" sincro:format="{{documento.unisincro.mime-type}}">
            <ID sincro:scheme="recepta.regis">{{documento.doc-id}}</ID>
            <Path>file://{{documento.unisincro.file-name}}</Path>
            <Hash sincro:hashFunction="{{documento.unisincro.hash-alg}}">{{documento.unisincro.hash}}</Hash>
            <MoreInfo sincro:xmlSchema="https://www.esignum.it/schemas/cartellecliniche.xsd">
                <EmbeddedMetadata>
                  <Documento numeroPagina="{{documento.doc-npagina}}" fronteRetro="{{documento.doc-fronteretro}}" gruppo="{{documento.doc-gruppo}}"
  	              classificazioneId="{{documento.doc-classificazione}}" classificazioneDescrizione="{{documento.doc-classificazione-desc}}" dataCreazione="{{documento.doc-datacreazione|date:yyyy-MM-dd}}" />
                </EmbeddedMetadata>
            </MoreInfo>
        </File>{% endfor %}
    </FileGroup>
    <Process>
        <Submitter sincro:agentType="legal person">
            <AgentID sincro:nameRegistrationAuthority="Agenzia delle Entrate">VATIT-01111630495</AgentID>
            <AgentName>
                <FormalName>Marno S.r.l.</FormalName>
            </AgentName>
            <RelevantDocument>Manuale della conservazione</RelevantDocument>
        </Submitter>
        <Holder sincro:holderRole="soggetto produttore" sincro:agentType="legal person">
            <AgentID sincro:nameRegistrationAuthority="Ministero della Salute">MS:IT-{{cartella-presidio-codice}}</AgentID>
            <AgentName>
                <FormalName>{{cartella-presidio-descrizione}}</FormalName>
            </AgentName>
            <RelevantDocument>Manuale della conservazione</RelevantDocument>
        </Holder>
        <AuthorizedSigner sincro:signerRole="PreservationManager" sincro:agentType="natural person">
            <AgentID sincro:nameRegistrationAuthority="Agenzia delle Entrate">TINIT-VLPNRC76R28G702X</AgentID>
            <AgentName>
                <NameAndSurname>
                    <FirstName>Enrico</FirstName>
                    <LastName>Volpato</LastName>
                </NameAndSurname>
            </AgentName>
            <RelevantDocument>Manuale della conservazione</RelevantDocument>
        </AuthorizedSigner>
        <AuthorizedSigner sincro:signerRole="Delegate" sincro:agentType="natural person">
            <AgentID sincro:nameRegistrationAuthority="Agenzia delle Entrate">TINIT-NREBRNMNC73R56E625X</AgentID>
            <AgentName>
                <NameAndSurname>
                    <FirstName>Monica</FirstName>
                    <LastName>Branchetti</LastName>
                </NameAndSurname>
                <RelevantDocument>Manuale della conservazione</RelevantDocument>
            </AgentName>
        </AuthorizedSigner>
        <TimeReference>
          <TimeInfo sincro:attachedTimeStamp="false">{{data-creazione}}</TimeInfo>
        </TimeReference>
        <LawsAndRegulations>UNI 11386:2020</LawsAndRegulations>
        <MoreInfo sincro:xmlSchema="https://www.esignum.it/schemas/cartellecliniche.xsd">
          <EmbeddedMetadata>
            <OperatoriCartella>
              <Operatore operazione="SCANSIONE" cognome="{{operatore-scansione.operatore-cognome}}" nome="{{operatore-scansione.operatore-nome}}" codiceFiscale="{{operatore-scansione.operatore-codfiscale}}" data="{{cartella-datascansione|date:yyyy-MM-dd}}" />
              <Operatore operazione="TIPIZZAZIONE" cognome="{{operatore-tipizzazione.operatore-cognome}}" nome="{{operatore-tipizzazione.operatore-nome}}" codiceFiscale="{{operatore-tipizzazione.operatore-codfiscale}}" data="{{cartella-datatipizzazione|date:yyyy-MM-dd}}" />
            </OperatoriCartella>
          </EmbeddedMetadata>
      </MoreInfo>
    </Process>
</PIndex>

=== filippocostalli/esignum-cco/resources/idc_uda_unisincro2020.xml
<?xml version="1.0" encoding="UTF-8"?>
<PIndex xmlns="http://www.uni.com/U3011/sincro-v2/"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.uni.com/U3011/sincro-v2 PIndex.xsd"
 xmlns:sincro="http://www.uni.com/U3011/sincro-v2/" sincro:language="it"
 sincro:uri="http://www.uni.com/U3011/sincro-v2/PIndex.xsd" sincro:sincroVersion="2.0">
    <SelfDescription>
        <ID sincro:scheme="recepta-regis">XXXXXXX</ID>
        <CreatingApplication>
            <Name>esignum</Name>
            <Version>2.0.0</Version>
            <Producer>Marno S.r.l.</Producer>
        </CreatingApplication>
    </SelfDescription>
    <PVolume>
        <ID sincro:scheme="recepta.regis">{{metadata.cartella_scatola}}_{{sesscamp_id}}</ID>
        <Label>UNITA' DI ARCHIVIAZIONE CARTELLE CLINICHE</Label>
        <Description>Contenitore virtuale cartelle cliniche</Description>
        <MoreInfo sincro:xmlSchema="https://www.esignum.it/schemas/cartellecliniche.xsd">
          <EmbeddedMetadata>
            <UnitaDiArchiviazioneCartelleCliniche
            codiceContenitore="{{metadata.cartella-scatola}}" indiceCampionamento="{{sesscamp-id}}"
            aziendaCodiceIpa="{{metadata.asl-ipa}}" aziendaDescrizione="{{metadata.asl-descrizione}}"
            />
          </EmbeddedMetadata>
        </MoreInfo>
    </PVolume>
    <FileGroup>
        <ID sincro:scheme="recepta.regis">XXXXX</ID>
        <Description>Lista degli indici delle varie cartelle inserite nel contenitore</Description>{% for idc-cartella in idc-cartelle %}
        <File sincro:encoding="binary" sincro:format="{{idc-cartella.mime-type}}">
            <ID sincro:scheme="recepta.regis">{{documento.doc-id}}</ID>
            <Path>file://{{idc-cartella.file-name}}</Path>
            <Hash sincro:hashFunction="{{idc-cartella.hash-alg}}">{{idc-cartella.hash}}</Hash>
        </File>{% endfor %}
    </FileGroup>
    <Process>
        <Submitter sincro:agentType="legal person">
            <AgentID sincro:nameRegistrationAuthority="Agenzia delle Entrate">VATIT-01111630495</AgentID>
            <AgentName>
                <FormalName>Marno S.r.l.</FormalName>
            </AgentName>
            <RelevantDocument>Manuale della conservazione</RelevantDocument>
        </Submitter>
        <Holder sincro:holderRole="soggetto produttore" sincro:agentType="legal person">
            <AgentID sincro:nameRegistrationAuthority="Ministero della Salute">MS:IT-{{cartella-presidio-codice}}</AgentID>
            <AgentName>
                <FormalName>{{cartella-presidio-descrizione}}</FormalName>
            </AgentName>
            <RelevantDocument>Manuale della conservazione</RelevantDocument>
        </Holder>
        <AuthorizedSigner sincro:signerRole="PreservationManager" sincro:agentType="natural person">
            <AgentID sincro:nameRegistrationAuthority="Agenzia delle Entrate">TINIT-VLPNRC76R28G702X</AgentID>
            <AgentName>
                <NameAndSurname>
                    <FirstName>Enrico</FirstName>
                    <LastName>Volpato</LastName>
                </NameAndSurname>
            </AgentName>
            <RelevantDocument>Manuale della conservazione</RelevantDocument>
        </AuthorizedSigner>
        <AuthorizedSigner sincro:signerRole="Delegate" sincro:agentType="natural person">
            <AgentID sincro:nameRegistrationAuthority="Agenzia delle Entrate">TINIT-NREBRNMNC73R56E625X</AgentID>
            <AgentName>
                <NameAndSurname>
                    <FirstName>Monica</FirstName>
                    <LastName>Branchetti</LastName>
                </NameAndSurname>
                <RelevantDocument>Manuale della conservazione</RelevantDocument>
            </AgentName>
        </AuthorizedSigner>
        <TimeReference>
          <TimeInfo sincro:attachedTimeStamp="false">{{data-creazione}}</TimeInfo>
        </TimeReference>
        <LawsAndRegulations>UNI 11386:2020</LawsAndRegulations>
        <MoreInfo sincro:xmlSchema="https://www.esignum.it/schemas/cartellecliniche.xsd">
          <EmbeddedMetadata>
            <Operatori>
              <Operatore operazione="CAMPIONAMENTO" cognome="{{utente-cognome}}" nome="{{utente-nome}}" codiceFiscale="{{utente-codfiscale}}" data="{{sesscamp-inizio|date:yyyy-MM-dd}}" />
            </Operatori>
          </EmbeddedMetadata>
      </MoreInfo>
    </Process>
</PIndex>
